builds:
- main: ./cmd/gotmpl/main.go
  env:
    - CGO_ENABLED=0
  goos:
    - linux
    - windows
    - darwin
  targets:
    - gotmpl
archives:
- name: gotmpl
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip
